//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace Web.WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CadastrarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback EfetuarLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarContaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarReceitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarContasOperationCompleted;
        
        private System.Threading.SendOrPostCallback AlterarSenhaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::Web.Properties.Settings.Default.Web_WebService_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CadastrarUsuarioCompletedEventHandler CadastrarUsuarioCompleted;
        
        /// <remarks/>
        public event EfetuarLoginCompletedEventHandler EfetuarLoginCompleted;
        
        /// <remarks/>
        public event CadastrarContaCompletedEventHandler CadastrarContaCompleted;
        
        /// <remarks/>
        public event CadastrarCategoriaCompletedEventHandler CadastrarCategoriaCompleted;
        
        /// <remarks/>
        public event CadastrarReceitaCompletedEventHandler CadastrarReceitaCompleted;
        
        /// <remarks/>
        public event ListarContasCompletedEventHandler ListarContasCompleted;
        
        /// <remarks/>
        public event AlterarSenhaCompletedEventHandler AlterarSenhaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CadastrarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CadastrarUsuario(string nome, string email, string login, string senha) {
            object[] results = this.Invoke("CadastrarUsuario", new object[] {
                        nome,
                        email,
                        login,
                        senha});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CadastrarUsuarioAsync(string nome, string email, string login, string senha) {
            this.CadastrarUsuarioAsync(nome, email, login, senha, null);
        }
        
        /// <remarks/>
        public void CadastrarUsuarioAsync(string nome, string email, string login, string senha, object userState) {
            if ((this.CadastrarUsuarioOperationCompleted == null)) {
                this.CadastrarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarUsuarioOperationCompleted);
            }
            this.InvokeAsync("CadastrarUsuario", new object[] {
                        nome,
                        email,
                        login,
                        senha}, this.CadastrarUsuarioOperationCompleted, userState);
        }
        
        private void OnCadastrarUsuarioOperationCompleted(object arg) {
            if ((this.CadastrarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarUsuarioCompleted(this, new CadastrarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EfetuarLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuario EfetuarLogin(string login, string senha) {
            object[] results = this.Invoke("EfetuarLogin", new object[] {
                        login,
                        senha});
            return ((Usuario)(results[0]));
        }
        
        /// <remarks/>
        public void EfetuarLoginAsync(string login, string senha) {
            this.EfetuarLoginAsync(login, senha, null);
        }
        
        /// <remarks/>
        public void EfetuarLoginAsync(string login, string senha, object userState) {
            if ((this.EfetuarLoginOperationCompleted == null)) {
                this.EfetuarLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEfetuarLoginOperationCompleted);
            }
            this.InvokeAsync("EfetuarLogin", new object[] {
                        login,
                        senha}, this.EfetuarLoginOperationCompleted, userState);
        }
        
        private void OnEfetuarLoginOperationCompleted(object arg) {
            if ((this.EfetuarLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EfetuarLoginCompleted(this, new EfetuarLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CadastrarConta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CadastrarConta(string nome, decimal saldo, string descricao, int fk_usu_id) {
            object[] results = this.Invoke("CadastrarConta", new object[] {
                        nome,
                        saldo,
                        descricao,
                        fk_usu_id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CadastrarContaAsync(string nome, decimal saldo, string descricao, int fk_usu_id) {
            this.CadastrarContaAsync(nome, saldo, descricao, fk_usu_id, null);
        }
        
        /// <remarks/>
        public void CadastrarContaAsync(string nome, decimal saldo, string descricao, int fk_usu_id, object userState) {
            if ((this.CadastrarContaOperationCompleted == null)) {
                this.CadastrarContaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarContaOperationCompleted);
            }
            this.InvokeAsync("CadastrarConta", new object[] {
                        nome,
                        saldo,
                        descricao,
                        fk_usu_id}, this.CadastrarContaOperationCompleted, userState);
        }
        
        private void OnCadastrarContaOperationCompleted(object arg) {
            if ((this.CadastrarContaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarContaCompleted(this, new CadastrarContaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CadastrarCategoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CadastrarCategoria(string categoria, int usuario) {
            object[] results = this.Invoke("CadastrarCategoria", new object[] {
                        categoria,
                        usuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CadastrarCategoriaAsync(string categoria, int usuario) {
            this.CadastrarCategoriaAsync(categoria, usuario, null);
        }
        
        /// <remarks/>
        public void CadastrarCategoriaAsync(string categoria, int usuario, object userState) {
            if ((this.CadastrarCategoriaOperationCompleted == null)) {
                this.CadastrarCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarCategoriaOperationCompleted);
            }
            this.InvokeAsync("CadastrarCategoria", new object[] {
                        categoria,
                        usuario}, this.CadastrarCategoriaOperationCompleted, userState);
        }
        
        private void OnCadastrarCategoriaOperationCompleted(object arg) {
            if ((this.CadastrarCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarCategoriaCompleted(this, new CadastrarCategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CadastrarReceita", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CadastrarReceita(int idConta, decimal valor) {
            object[] results = this.Invoke("CadastrarReceita", new object[] {
                        idConta,
                        valor});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CadastrarReceitaAsync(int idConta, decimal valor) {
            this.CadastrarReceitaAsync(idConta, valor, null);
        }
        
        /// <remarks/>
        public void CadastrarReceitaAsync(int idConta, decimal valor, object userState) {
            if ((this.CadastrarReceitaOperationCompleted == null)) {
                this.CadastrarReceitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarReceitaOperationCompleted);
            }
            this.InvokeAsync("CadastrarReceita", new object[] {
                        idConta,
                        valor}, this.CadastrarReceitaOperationCompleted, userState);
        }
        
        private void OnCadastrarReceitaOperationCompleted(object arg) {
            if ((this.CadastrarReceitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarReceitaCompleted(this, new CadastrarReceitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarContas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Conta[] ListarContas(int usuario) {
            object[] results = this.Invoke("ListarContas", new object[] {
                        usuario});
            return ((Conta[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarContasAsync(int usuario) {
            this.ListarContasAsync(usuario, null);
        }
        
        /// <remarks/>
        public void ListarContasAsync(int usuario, object userState) {
            if ((this.ListarContasOperationCompleted == null)) {
                this.ListarContasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarContasOperationCompleted);
            }
            this.InvokeAsync("ListarContas", new object[] {
                        usuario}, this.ListarContasOperationCompleted, userState);
        }
        
        private void OnListarContasOperationCompleted(object arg) {
            if ((this.ListarContasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarContasCompleted(this, new ListarContasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AlterarSenha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AlterarSenha(int usuario, string senhaAntiga, string senhaNova) {
            object[] results = this.Invoke("AlterarSenha", new object[] {
                        usuario,
                        senhaAntiga,
                        senhaNova});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AlterarSenhaAsync(int usuario, string senhaAntiga, string senhaNova) {
            this.AlterarSenhaAsync(usuario, senhaAntiga, senhaNova, null);
        }
        
        /// <remarks/>
        public void AlterarSenhaAsync(int usuario, string senhaAntiga, string senhaNova, object userState) {
            if ((this.AlterarSenhaOperationCompleted == null)) {
                this.AlterarSenhaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAlterarSenhaOperationCompleted);
            }
            this.InvokeAsync("AlterarSenha", new object[] {
                        usuario,
                        senhaAntiga,
                        senhaNova}, this.AlterarSenhaOperationCompleted, userState);
        }
        
        private void OnAlterarSenhaOperationCompleted(object arg) {
            if ((this.AlterarSenhaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AlterarSenhaCompleted(this, new AlterarSenhaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuario {
        
        private int usu_idField;
        
        private string usu_nomeField;
        
        private string usu_emailField;
        
        private string usu_loginField;
        
        private string usu_senhaField;
        
        private int usu_statusField;
        
        /// <remarks/>
        public int Usu_id {
            get {
                return this.usu_idField;
            }
            set {
                this.usu_idField = value;
            }
        }
        
        /// <remarks/>
        public string Usu_nome {
            get {
                return this.usu_nomeField;
            }
            set {
                this.usu_nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Usu_email {
            get {
                return this.usu_emailField;
            }
            set {
                this.usu_emailField = value;
            }
        }
        
        /// <remarks/>
        public string Usu_login {
            get {
                return this.usu_loginField;
            }
            set {
                this.usu_loginField = value;
            }
        }
        
        /// <remarks/>
        public string Usu_senha {
            get {
                return this.usu_senhaField;
            }
            set {
                this.usu_senhaField = value;
            }
        }
        
        /// <remarks/>
        public int Usu_status {
            get {
                return this.usu_statusField;
            }
            set {
                this.usu_statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Conta {
        
        private int cont_idField;
        
        private string cont_nomeField;
        
        private decimal cont_saldoField;
        
        private string cont_descricaoField;
        
        private int fk_usu_idField;
        
        /// <remarks/>
        public int Cont_id {
            get {
                return this.cont_idField;
            }
            set {
                this.cont_idField = value;
            }
        }
        
        /// <remarks/>
        public string Cont_nome {
            get {
                return this.cont_nomeField;
            }
            set {
                this.cont_nomeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Cont_saldo {
            get {
                return this.cont_saldoField;
            }
            set {
                this.cont_saldoField = value;
            }
        }
        
        /// <remarks/>
        public string Cont_descricao {
            get {
                return this.cont_descricaoField;
            }
            set {
                this.cont_descricaoField = value;
            }
        }
        
        /// <remarks/>
        public int Fk_usu_id {
            get {
                return this.fk_usu_idField;
            }
            set {
                this.fk_usu_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CadastrarUsuarioCompletedEventHandler(object sender, CadastrarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CadastrarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CadastrarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EfetuarLoginCompletedEventHandler(object sender, EfetuarLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EfetuarLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EfetuarLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuario Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuario)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CadastrarContaCompletedEventHandler(object sender, CadastrarContaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CadastrarContaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CadastrarContaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CadastrarCategoriaCompletedEventHandler(object sender, CadastrarCategoriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CadastrarCategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CadastrarCategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CadastrarReceitaCompletedEventHandler(object sender, CadastrarReceitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CadastrarReceitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CadastrarReceitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListarContasCompletedEventHandler(object sender, ListarContasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarContasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarContasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Conta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Conta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AlterarSenhaCompletedEventHandler(object sender, AlterarSenhaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AlterarSenhaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AlterarSenhaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591