//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Entidades
{
    public partial class tb_categoria
    {
        #region Primitive Properties
    
        public virtual long cat_id
        {
            get;
            set;
        }
    
        public virtual string cat_nome
        {
            get;
            set;
        }
    
        public virtual long fk_usu_id
        {
            get { return _fk_usu_id; }
            set
            {
                if (_fk_usu_id != value)
                {
                    if (tb_usuario != null && tb_usuario.usu_id != value)
                    {
                        tb_usuario = null;
                    }
                    _fk_usu_id = value;
                }
            }
        }
        private long _fk_usu_id;

        #endregion
        #region Navigation Properties
    
        public virtual tb_usuario tb_usuario
        {
            get;
            set;
        }
    
        public virtual ICollection<tb_transacao> tb_transacao
        {
            get;
            set;
        }     

        #endregion
        
    }
}
