//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Entidades
{
    public partial class tb_categoria
    {
        #region Primitive Properties
    
        public virtual long cat_id
        {
            get;
            set;
        }
    
        public virtual string cat_nome
        {
            get;
            set;
        }
    
        public virtual long fk_usu_id
        {
            get { return _fk_usu_id; }
            set
            {
                if (_fk_usu_id != value)
                {
                    if (tb_usuario != null && tb_usuario.usu_id != value)
                    {
                        tb_usuario = null;
                    }
                    _fk_usu_id = value;
                }
            }
        }
        private long _fk_usu_id;

        #endregion
        #region Navigation Properties
    
        public virtual tb_usuario tb_usuario
        {
            get { return _tb_usuario; }
            set
            {
                if (!ReferenceEquals(_tb_usuario, value))
                {
                    var previousValue = _tb_usuario;
                    _tb_usuario = value;
                    Fixuptb_usuario(previousValue);
                }
            }
        }
        private tb_usuario _tb_usuario;
    
        public virtual ICollection<tb_transacao> tb_transacao
        {
            get
            {
                if (_tb_transacao == null)
                {
                    var newCollection = new FixupCollection<tb_transacao>();
                    newCollection.CollectionChanged += Fixuptb_transacao;
                    _tb_transacao = newCollection;
                }
                return _tb_transacao;
            }
            set
            {
                if (!ReferenceEquals(_tb_transacao, value))
                {
                    var previousValue = _tb_transacao as FixupCollection<tb_transacao>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptb_transacao;
                    }
                    _tb_transacao = value;
                    var newValue = value as FixupCollection<tb_transacao>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptb_transacao;
                    }
                }
            }
        }
        private ICollection<tb_transacao> _tb_transacao;

        #endregion
        #region Association Fixup
    
        private void Fixuptb_usuario(tb_usuario previousValue)
        {
            if (previousValue != null && previousValue.tb_categoria.Contains(this))
            {
                previousValue.tb_categoria.Remove(this);
            }
    
            if (tb_usuario != null)
            {
                if (!tb_usuario.tb_categoria.Contains(this))
                {
                    tb_usuario.tb_categoria.Add(this);
                }
                if (fk_usu_id != tb_usuario.usu_id)
                {
                    fk_usu_id = tb_usuario.usu_id;
                }
            }
        }
    
        private void Fixuptb_transacao(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tb_transacao item in e.NewItems)
                {
                    item.tb_categoria = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tb_transacao item in e.OldItems)
                {
                    if (ReferenceEquals(item.tb_categoria, this))
                    {
                        item.tb_categoria = null;
                    }
                }
            }
        }

        #endregion
    }
}
