//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Entidades
{
    public partial class tb_transacao
    {
        #region Primitive Properties
    
        public virtual long trans_id
        {
            get;
            set;
        }
    
        public virtual System.DateTime trans_data
        {
            get;
            set;
        }
    
        public virtual decimal trans_valor
        {
            get;
            set;
        }
    
        public virtual string trans_descricao
        {
            get;
            set;
        }
    
        public virtual long fk_tip_id
        {
            get { return _fk_tip_id; }
            set
            {
                if (_fk_tip_id != value)
                {
                    if (tb_tipo != null && tb_tipo.tip_id != value)
                    {
                        tb_tipo = null;
                    }
                    _fk_tip_id = value;
                }
            }
        }
        private long _fk_tip_id;
    
        public virtual long fk_cont_id
        {
            get { return _fk_cont_id; }
            set
            {
                if (_fk_cont_id != value)
                {
                    if (tb_conta != null && tb_conta.cont_id != value)
                    {
                        tb_conta = null;
                    }
                    _fk_cont_id = value;
                }
            }
        }
        private long _fk_cont_id;
    
        public virtual long fk_cat_id
        {
            get { return _fk_cat_id; }
            set
            {
                if (_fk_cat_id != value)
                {
                    if (tb_categoria != null && tb_categoria.cat_id != value)
                    {
                        tb_categoria = null;
                    }
                    _fk_cat_id = value;
                }
            }
        }
        private long _fk_cat_id;

        #endregion
        #region Navigation Properties
    
        public virtual tb_categoria tb_categoria
        {
            get { return _tb_categoria; }
            set
            {
                if (!ReferenceEquals(_tb_categoria, value))
                {
                    var previousValue = _tb_categoria;
                    _tb_categoria = value;
                    Fixuptb_categoria(previousValue);
                }
            }
        }
        private tb_categoria _tb_categoria;
    
        public virtual tb_conta tb_conta
        {
            get { return _tb_conta; }
            set
            {
                if (!ReferenceEquals(_tb_conta, value))
                {
                    var previousValue = _tb_conta;
                    _tb_conta = value;
                    Fixuptb_conta(previousValue);
                }
            }
        }
        private tb_conta _tb_conta;
    
        public virtual tb_tipo tb_tipo
        {
            get { return _tb_tipo; }
            set
            {
                if (!ReferenceEquals(_tb_tipo, value))
                {
                    var previousValue = _tb_tipo;
                    _tb_tipo = value;
                    Fixuptb_tipo(previousValue);
                }
            }
        }
        private tb_tipo _tb_tipo;

        #endregion
        #region Association Fixup
    
        private void Fixuptb_categoria(tb_categoria previousValue)
        {
            if (previousValue != null && previousValue.tb_transacao.Contains(this))
            {
                previousValue.tb_transacao.Remove(this);
            }
    
            if (tb_categoria != null)
            {
                if (!tb_categoria.tb_transacao.Contains(this))
                {
                    tb_categoria.tb_transacao.Add(this);
                }
                if (fk_cat_id != tb_categoria.cat_id)
                {
                    fk_cat_id = tb_categoria.cat_id;
                }
            }
        }
    
        private void Fixuptb_conta(tb_conta previousValue)
        {
            if (previousValue != null && previousValue.tb_transacao.Contains(this))
            {
                previousValue.tb_transacao.Remove(this);
            }
    
            if (tb_conta != null)
            {
                if (!tb_conta.tb_transacao.Contains(this))
                {
                    tb_conta.tb_transacao.Add(this);
                }
                if (fk_cont_id != tb_conta.cont_id)
                {
                    fk_cont_id = tb_conta.cont_id;
                }
            }
        }
    
        private void Fixuptb_tipo(tb_tipo previousValue)
        {
            if (previousValue != null && previousValue.tb_transacao.Contains(this))
            {
                previousValue.tb_transacao.Remove(this);
            }
    
            if (tb_tipo != null)
            {
                if (!tb_tipo.tb_transacao.Contains(this))
                {
                    tb_tipo.tb_transacao.Add(this);
                }
                if (fk_tip_id != tb_tipo.tip_id)
                {
                    fk_tip_id = tb_tipo.tip_id;
                }
            }
        }

        #endregion
    }
}
