//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Entidades
{
    public partial class tb_tipo
    {
        #region Primitive Properties
    
        public virtual long tip_id
        {
            get;
            set;
        }
    
        public virtual string tip_nome
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<tb_transacao> tb_transacao
        {
            get
            {
                if (_tb_transacao == null)
                {
                    var newCollection = new FixupCollection<tb_transacao>();
                    newCollection.CollectionChanged += Fixuptb_transacao;
                    _tb_transacao = newCollection;
                }
                return _tb_transacao;
            }
            set
            {
                if (!ReferenceEquals(_tb_transacao, value))
                {
                    var previousValue = _tb_transacao as FixupCollection<tb_transacao>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixuptb_transacao;
                    }
                    _tb_transacao = value;
                    var newValue = value as FixupCollection<tb_transacao>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixuptb_transacao;
                    }
                }
            }
        }
        private ICollection<tb_transacao> _tb_transacao;

        #endregion
        #region Association Fixup
    
        private void Fixuptb_transacao(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (tb_transacao item in e.NewItems)
                {
                    item.tb_tipo = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (tb_transacao item in e.OldItems)
                {
                    if (ReferenceEquals(item.tb_tipo, this))
                    {
                        item.tb_tipo = null;
                    }
                }
            }
        }

        #endregion
    }
}
