//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Entidades
{
    public partial class tb_usuario
    {
        #region Primitive Properties
    
        public virtual long usu_id
        {
            get;
            set;
        }
    
        public virtual string usu_nome
        {
            get;
            set;
        }
    
        public virtual string usu_email
        {
            get;
            set;
        }
    
        public virtual string usu_login
        {
            get;
            set;
        }
    
        public virtual string usu_senha
        {
            get;
            set;
        }
    
        public virtual byte usu_status
        {
            get;
            set;
        }

        #endregion
       
        
    }
}
