//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace Data
{
    public partial class controle_gastosEntities : ObjectContext
    {
        public const string ConnectionString = "name=controle_gastosEntities";
        public const string ContainerName = "controle_gastosEntities";
    
        #region Constructors
    
        public controle_gastosEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public controle_gastosEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public controle_gastosEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<tb_categoria> tb_categoria
        {
            get { return _tb_categoria  ?? (_tb_categoria = CreateObjectSet<tb_categoria>("tb_categoria")); }
        }
        private ObjectSet<tb_categoria> _tb_categoria;
    
        public ObjectSet<tb_conta> tb_conta
        {
            get { return _tb_conta  ?? (_tb_conta = CreateObjectSet<tb_conta>("tb_conta")); }
        }
        private ObjectSet<tb_conta> _tb_conta;
    
        public ObjectSet<tb_tipo> tb_tipo
        {
            get { return _tb_tipo  ?? (_tb_tipo = CreateObjectSet<tb_tipo>("tb_tipo")); }
        }
        private ObjectSet<tb_tipo> _tb_tipo;
    
        public ObjectSet<tb_transacao> tb_transacao
        {
            get { return _tb_transacao  ?? (_tb_transacao = CreateObjectSet<tb_transacao>("tb_transacao")); }
        }
        private ObjectSet<tb_transacao> _tb_transacao;
    
        public ObjectSet<tb_usuario> tb_usuario
        {
            get { return _tb_usuario  ?? (_tb_usuario = CreateObjectSet<tb_usuario>("tb_usuario")); }
        }
        private ObjectSet<tb_usuario> _tb_usuario;

        #endregion
    }
}
